### ISSUE TITLE
Create root partition task fails if the device already has partitions

### ISSUE THREAD

**Issue by SlothOfAnarchy** [stuvusIT/bootstrap-ubuntu-rpi3#7]

**Comment by dasJ** [comment]
Automatically bumping this issue because it was inactive for 80 days.

**Comment by dasJ** [comment]
Automatically bumping this issue because it was inactive for 87 days.

**Comment by dasJ** [comment]
Automatically bumping this issue because it was inactive for 130 days.

**Comment by dasJ** [comment]
Automatically bumping this issue because it was inactive for 149 days.

**Comment by dasJ** [comment]
Automatically bumping this issue because it was inactive for 606 days.

**Comment by dasJ** [comment]
Automatically bumping this issue because it was inactive for 772 days.

**Comment by haslersn** [comment]
We archive this repository.
